-- Crear registros
INSERT INTO University.Student (RollNo, Name, dept, semester) VALUES (1, 'John Doe', 'Computer Science', 3);
INSERT INTO University.Student (RollNo, Name, dept, semester) VALUES (2, 'Jane Smith', 'Mathematics', 2);
INSERT INTO University.Student (RollNo, Name, dept, semester) VALUES (3, 'Alice Johnson', 'Physics', 1);
INSERT INTO University.Student (RollNo, Name, dept, semester) VALUES (4, 'Bob Brown', 'Chemistry', 4);

-- Vaciar tabla
Truncate University.Student;